### ISSUE TITLE
Wiki Documents

### ISSUE THREAD

**Issue by anastassia-b** [Mpompili/vibesky#1]
Hey Michael,

Great work on your full stack proposal! I've had the chance to review it and here is my feedback:

# Wiki Page Home

- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page:
  - [x] Only the MVP bullet link doesn't work! Please update.
- [x] Correctly formatted

# MVP List

- [x] Should have 7 MVPs
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or otherwise clarified.
- [x] Contains a description sentence of the app
- [x] At least one-two CRUD features
  - [x] Each feature states [what CRUD operations are planned](https://github.com/appacademy/bluebird/wiki/mvp-list) (creating, reading, editing, deleting).
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

### Comments:

What do you think about the following change to the MVPs?
- [x] Adding `Likes` as a very basic POST/DELETE resource, as part of the   `User Profile MVP`. That way a user's profile page can display:
  * A user's uploaded tracks (but for most users this will be none?)
  * A track list index of the user's liked tracks (fills up most of the page).
* If you feel like adding Likes is too much for MVPs, let me know and we can see if we can pare down some other MVP.

Note: When you later open each app-specific MVP as an issue, in the issue description please have the following bullets:
  + Adequate styling
  + Smooth, bug-free navigation
  + Seeded with info to demonstrate this feature
These will be required for an MVP to be considered complete.

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] index
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

### Comments:

- [x] Your schema is missing indexes. What is the purpose of indexing and which columns do we want indexes on?
- [x] Can you change the two `user_id` columns to be more semantic? For example, `liker_id` or `uploader_id`? That way the association `user.tracks` can be more clear-- is it the users liked tracks, or uploaded tracks?

# Routes

* Contains the following sections:
  - [ ] HTML (what will your React app hook on to?)
  - [x] API Endpoints(Backend)
  - [x] Frontend Routes
- [x] Routes accurately reflect MVPs and Component Hierarchy
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  - [x] For example, `GET /api/tracks/:id/comments - get comments on specific track` may be extraneous. For the track show page, the comments can be fetched together with this request: `GET /api/tracks/:track_id - get specific track`.
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

### Comments:

- [x] `GET /api/users - get user info`: This route does not match the description. Are you getting all users, or a specific user?
- [x] For PATCH and DELETE for comments, we can access a comment directly with a comment id. We do not need to nest it under track/:track_id.
- [x] Please add two routes for Likes: POST and DELETE.

# Sample State

- [x] State shape is flat! Should NOT have nested slices, though some info from other tables is ok.
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema/model
- [x] Correctly formatted

### Comments:
- [x] Missing some information: Please store a commentIds array with each track. This can be built with jBuilder on the backend. (similar in concept to how each pokemon kept track of their itemIds).-
- [x] Potentially you may want to store additional things as your project proceeds, such as song duration, etc.
- [x] How will likes be represented/stored in this state?

# Component Hierarchy with Wireframes
- [x] All routes listed in the routes wiki page is also listed in the component hierarchy
- [x] Each component, if necessary, has route, state, and other components it renders example
- [x] Necessary components are wrapped in a container
- [x] Wireframes included for each MVP/route/etc.

**Comment by Mpompili** [comment]
Made the corrections! :]

**Comment by anastassia-b** [comment]
Excellent job addressing all the feedback! We discussed adding stronger database constraints. You also fixed the state shape-- removing sensitive user information like `session_token`. RECEIVE_CURRENT_USER is different from RECEIVE_USER, which answers your question about storing other users vs the current user. Thanks!
