### ISSUE TITLE
PA Review: Hosting on Heroku

### ISSUE THREAD

**Issue by Mpompili** [Mpompili/vibesky#2]
## Initial Deployment:
- [x] Initial push to heroku

## Final Deployment:
- [x] Remove console statements: debuggers, console.logs, errors, minification warnings, mixed content warnings
- [x] Use dev tools in dev environment

## Bonus:
- [ ] Custom domain name

**Comment by Mpompili** [comment]
https://vibesky.herokuapp.com/

:D

**Comment by Mpompili** [comment]
@anastassia-b this should good now

**Comment by anastassia-b** [comment]
Great! We will close this MVP on W9D5, when you get your [app ready for production mode](https://github.com/appacademy/curriculum/blob/master/full-stack-project/resources/helpful_tools/production-ready.md) and make the final push.
